name: myapp
type: php:8.3
web:
  locations:
    "/":
      root: "v"
      passthru: "/index.php"  # Critical for PHP routing
      index:
        - index.php
      allow: true
      scripts: false  # Disable auto-PHP handling (let .htaccess manage it)
disk: 1024
