name: myapp
type: php:8.3
web:
  locations:
    "/v":  # Explicit /v endpoint
      root: "v"
      passthru: false  # Critical - hands control to your .htaccess
      index:
        - index.php
      allow: true
      scripts: true
disk: 1024
