name: myapp
type: php:8.3
web:
  locations:
    "/v":
      root: "v"
      passthru: "/v/index.php"
      index:
        - index.php
      allow: true
      scripts: true
    
    
    "/":
      passthru: false
      to: "/v/"  

disk: 1024
