name: myapp
type: php:8.3
web:
  locations:
    "/":  # Serve directly from root without /v/
      root: "v"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
      scripts: true  # Enable PHP processing
disk: 1024
