name: myapp
type: php:8.3
web:
  locations:
    "/":
      root: "v"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
      scripts: false  # CRITICAL - Disables Platform.sh's PHP handling
disk: 1024
