name: myapp
type: php:8.3
web:
  locations:
    "/v":
      root: "v"
      passthru: "/v/index.php"
      index:
        - index.php
      allow: true
      scripts: true
    
    # Correct way to redirect root to /v/
    "/":
      passthru: false
      rules:
        ".*":
          type: redirect
          to: "/v/"
          code: 301

disk: 1024
