name: myapp
type: php:8.3
web:
  locations:
    "/":  # Serve directly from root
      root: "v"
      passthru: "/index.php"
      index:
        - index.php
      allow: true
      scripts: false  # CRITICAL - Disable Platform.sh's PHP handling
disk: 1024
