name: myapp
type: php:8.3
web:
  locations:
    "/v":  # Explicit /v endpoint
      root: "v"
      passthru: "/v/index.php"  # Full path
      index:
        - index.php
      allow: true
      scripts: true
    "/":    # Redirect root to /v
      passthru: false
      redirect:
        code: 301
        to: "/v/"
disk: 1024
